version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
  open-pull-requests-limit: 10
  reviewers:
  - leocomelli
  assignees:
  - leocomelli
